#!/bin/sh
# postinst script for sabily

set -e

# Source debconf library:
. /usr/share/debconf/confmodule

case "$1" in
    configure|upgrade)
     if [ -x /usr/lib/gdm/gdm-set-default-session ] ; then
       /usr/lib/gdm/gdm-set-default-session --keep-old gnome-shell || true
     fi

    if [ -x /usr/lib/lightdm/lightdm-set-defaults ] ; then
        /usr/lib/lightdm/lightdm-set-defaults --keep-old --session=gnome-shell || true
    fi

      # Update firefox bookmarks:
      db_get sabily/replace-bookmarks || true
      if [ "$RET" = "true" ]; then
        for d in firefox firefox-3.0 firefox-3.5; do
          if [ -d /etc/$d/profile ]; then
            cp -f /usr/share/sabily/bookmarks.html /etc/$d/profile/
          fi
        done
        echo "Firefox bookmarks updated"
      fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0

