#!/bin/bash
BUILD_DIR=`mktemp -d`

function failure()
{
	echo "$@"
	exit 1
}

SCRIPT_DIR=`dirname "$0"`
BOOT_LANG=`cat "$SCRIPT_DIR/livecd_locale"`
REMASTER_HOME=$1
ISO_REMASTER_DIR="$REMASTER_HOME/remaster-iso"
REMASTER_DIR="$REMASTER_HOME/remaster-root"

pushd "$BUILD_DIR" || failure "Cannot change directory to $BUILD_DIR, error=$?"
if [ -e "$REMASTER_DIR"  ]; then
	cp -f /etc/resolv.conf "$REMASTER_DIR/etc/resolv.conf" || failure "Failed to copy resolv.conf to image directory, error=$?"
	cp -a "$SCRIPT_DIR/download-gfxboot-theme-ubuntu" "$REMASTER_DIR/tmp"
	#chroot "$REMASTER_DIR" /tmp/download-gfxboot-theme-ubuntu || failure "Failed to fetch gfxboot-theme-ubuntu source, check if you have deb-src line enabled for repository main in /etc/apt/sources.list, error=$?"
	bzr get http://bazaar.launchpad.net/~ubuntu-core-dev/gfxboot-theme-ubuntu/mainline && mv mainline gfxboot-theme-ubuntu
	#mv "$REMASTER_DIR/tmp/gfxboot-theme-ubuntu" "$BUILD_DIR"
	chroot "$REMASTER_DIR" rm /etc/resolv.conf /tmp/download-gfxboot-theme-ubuntu /tmp/gfxboot*
else
	#apt-get source gfxboot-theme-ubuntu || failure "Failed to fetch gfxboot-theme-ubuntu source, check if you have deb-src line enabled for repository main in /etc/apt/sources.list, error=$?"
	bzr get http://bazaar.launchpad.net/~ubuntu-core-dev/gfxboot-theme-ubuntu/mainline && mv mainline gfxboot-theme-ubuntu
fi

cd gfxboot-theme-ubuntu*/

LIVECD_LANGS=`cat "$SCRIPT_DIR/language_packs"`
LANGPACKS_CONCATENATED=""

for LANGPACK in $LIVECD_LANGS; do
	if [ -z "$LANGPACKS_CONCATENATED" ]; then
		LANGPACKS_CONCATENATED="$LANGPACK"
	else
		LANGPACKS_CONCATENATED="$LANGPACKS_CONCATENATED|$LANGPACK"
	fi
done

make DEFAULT_LANG="$BOOT_LANG" || failure "Failed to build gfxboot theme, error=$?"
pushd boot
#fix list of languages to contain all languages for which there are language packs on CD
ls -1 *.tr | while read i ; do echo $(basename $i .tr) ; done | grep -E "^($LANGPACKS_CONCATENATED)\>(_.*)?" >langlist
popd

cp -af boot/* "$ISO_REMASTER_DIR/isolinux/" || failure "Error while copying boot files ( " boot/* " ) to $ISO_REMASTER_DIR/isolinux/, error=$?"

popd

if [ "$BUILD_DIR" = "/" ] ; then
	failure "Trying to remove root dir"
else
	rm -rf "$BUILD_DIR"
fi

#copy kernel and initrd, in case it was changed during installation
VMLINUZ=`ls -1 "$REMASTER_DIR"/boot/vmlinuz* | sort | tail -n1`
INITRD="$REMASTER_DIR"/boot/initrd.img-$(echo `basename $VMLINUZ` | cut -d'-' -f 2-)
if [ -e "$VMLINUZ" -a -e "$INITRD" ]; then
	echo "Updating kernel, kernel=$VMLINUZ, initrd=$INITRD"
	cp -f "$VMLINUZ" "$ISO_REMASTER_DIR/casper/vmlinuz"
	cp -f "$INITRD" "$ISO_REMASTER_DIR/casper/initrd.gz"
else
	echo "Not updating kernel as initrd not present"
fi

#################################################
# SABILY customizations
#################################################
# bicon
cp -f ./resources/bicon_0.2.0-1_amd64.deb "$REMASTER_DIR"/tmp/bicon_0.2.0-1_amd64.deb
cp -f ./resources/bicon_0.2.0-1_i386.deb "$REMASTER_DIR"/tmp/bicon_0.2.0-1_i386.deb
chroot "$REMASTER_DIR" dpkg -i /tmp/bicon_0.2.0-1_amd64.deb
chroot "$REMASTER_DIR" dpkg -i /tmp/bicon_0.2.0-1_i386.deb
rm -f "$REMASTER_DIR"/tmp/bicon_0.2.0-1_amd64.deb
rm -f "$REMASTER_DIR"/tmp/bicon_0.2.0-1_i386.deb

# Thwab books
#cp -f ./resources/thwab-books_1.0-0ubuntu1~ppa1_all.deb "$REMASTER_DIR"/tmp/thwab-books_1.0-0ubuntu1~ppa1_all.deb
#chroot "$REMASTER_DIR" dpkg -i /tmp/thwab-books_1.0-0ubuntu1~ppa1_all.deb
#rm -f "$REMASTER_DIR"/tmp/thwab-books_1.0-0ubuntu1~ppa1_all.deb

# Customization
cp -f ./resources/apt-setup "$REMASTER_DIR"/usr/share/ubiquity/apt-setup

# Live CD splash
cp -f ./resources/splash1-14colors.pcx "$ISO_REMASTER_DIR/isolinux/splash.pcx"
sed -i "s|background=.*|background=0x1F6E0B|" "$ISO_REMASTER_DIR/isolinux/gfxboot.cfg"


# lock firefox by default
#cp -f ./resources/firefox.cfg "$REMASTER_DIR"/usr/lib/firefox-3.0b5/firefox.cfg
#sed -i "s|pref(\"general.config.obscure_value\", 13)|pref(\"general.config.obscure_value\", 0)|" "$REMASTER_DIR"/usr/lib/xulrunner-1.9b5/greprefs/all.js
cp -f ./resources/firefox.js "$REMASTER_DIR"/etc/firefox-3.0/pref/firefox.js

# overwrite .desktop files to display Islamic apps in the Islamic software menu
cp -f ./resources/minbar.desktop "$REMASTER_DIR"/usr/share/applications/minbar.desktop

# remove ubuntu backgrounds to free up some space
#rm -f "$REMASTER_DIR"/usr/share/backgrounds/space-01.jpg # 73.9 KB
#rm -f "$REMASTER_DIR"/usr/share/backgrounds/space-02.jpg # 81.9 KB
#rm -f "$REMASTER_DIR"/usr/share/backgrounds/space-03.jpg # 30.9 KB
#rm -f "$REMASTER_DIR"/usr/share/backgrounds/space-04.jpg # 76.5 KB
#rm -f "$REMASTER_DIR"/usr/share/backgrounds/space-05.jpg # 14.3 KB

# dansguardian configuration
cp -f ./resources/dansguardian/dansguardian.conf "$REMASTER_DIR"/etc/dansguardian/dansguardian.conf
cp -f ./resources/dansguardian/dansguardianf2.conf "$REMASTER_DIR"/etc/dansguardian/dansguardianf2.conf
cp -f ./resources/dansguardian/bannedsitelist "$REMASTER_DIR"/etc/dansguardian/bannedsitelist
cp -f ./resources/dansguardian/bannedurllist "$REMASTER_DIR"/etc/dansguardian/bannedurllist
cp -f ./resources/dansguardian/bannedmimetypelist "$REMASTER_DIR"/etc/dansguardian/bannedmimetypelist
cp -f ./resources/dansguardian/bannedextensionlist "$REMASTER_DIR"/etc/dansguardian/bannedextensionlist
cp -f ./resources/dansguardian/default/oidentd "$REMASTER_DIR"/etc/default/oidentd
cp -f ./resources/dansguardian/tinyproxy/tinyproxy.conf "$REMASTER_DIR"/etc/tinyproxy/tinyproxy.conf
cp -rf ./resources/dansguardian/languages "$REMASTER_DIR"/etc/dansguardian
chroot "$REMASTER_DIR" dpkg-reconfigure dansguardian

chroot "$REMASTER_DIR" dpkg-reconfigure sabily-artwork

# choose sun java
chroot "$REMASTER_DIR" update-alternatives --config java


echo "Done customize_iso.sh"





